=== TiJ-code/Registermaschine/changelogs/patch.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT patch (category*)>
<!ELEMENT category (breaking*, additions?, refactorings?, fixes?, removals?)>
<!ELEMENT additions (entry*)>
<!ELEMENT refactorings (entry*)>
<!ELEMENT fixes (entry*)>
<!ELEMENT removals (entry*)>
<!ELEMENT entry (#PCDATA)>
<!ELEMENT breaking (additions?, refactorings?, fixes?, removals?)>
<!ATTLIST category name (api|core|instructions|dev-tools) #REQUIRED>
<!ATTLIST breaking kind (trivial|minor|major) #REQUIRED>

=== TiJ-code/Registermaschine/changelogs/patches/v1_1_0_p02_logging_system.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE patch SYSTEM "../patch.dtd">
<patch>
    <category name="api">
        <additions>
            <entry>ILogger interface for logger instances</entry>
            <entry>DefaultLogger, that provides a default implementation of a logger</entry>
            <entry>LoggerFactory, to create class specific instances</entry>
            <entry>LogConfig, a global config Logger instances must conform to</entry>
            <entry>LogLevel enum to display severity of log messages</entry>
        </additions>
    </category>
    <category name="core">
        <refactorings>
            <entry>every file to use the Logging API</entry>
        </refactorings>
    </category>
</patch>

=== TiJ-code/Registermaschine/changelogs/patches/v2_0_0_p01_multiple_instruction_handlers.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE patch SYSTEM "../patch.dtd">
<patch>
    <category name="api">
        <breaking kind="major">
            <additions>
                <entry>ChainedInstruction class, representing a new full instruction orchestrator</entry>
                <entry>IStepHandler interface, representing an atomic executable step handler</entry>
                <entry>ICompiledStep interface, representing the compiled variant of a step handler</entry>
                <entry>ConfigStep record, representing the structure parsed from the XML file</entry>
            </additions>
            <refactorings>
                <entry>IInstructionSet to store new instruction layout</entry>
                <entry>IStepHandlerRegistry, to take the responsibility of an singleton step handler registry</entry>
                <entry>PluginContext, to use IStepHandlerRegistry instead</entry>
            </refactorings>
            <removals>
                <entry>AbstractInstruction, since it is not required in the new instruction layout</entry>
                <entry>IInstructionRegistry, since the concept of instructions was removed</entry>
            </removals>
        </breaking>
        <breaking kind="trivial">
            <refactorings>
                <entry>ConfigInstruction, by moving it to `dk.tij.registermaschine.api.config.model`</entry>
                <entry>ConfigOperand, by moving it to `dk.tij.registermaschine.api.config.model`</entry>
            </refactorings>
        </breaking>
        <additions>
            <entry>InvalidOperandException, to make error reporting more precise</entry>
            <entry>IPrecompilerStage interface, to add stageable precompilation of config instructions to real instructions</entry>
        </additions>
    </category>
    <category name="core">
        <breaking kind="major">
            <refactorings>
                <entry>DTD for instruction files completely</entry>
                <entry>InstructionParser to parse according to the new file structure</entry>
                <entry>ConcreteCompiler, to compile the new instruction layout</entry>
                <entry>Executor, to work with new instruction layout</entry>
            </refactorings>
        </breaking>
        <breaking kind="trivial">
            <refactorings>
                <entry>ConcreteInstructionSet, by moving it to `dk.tij.registermaschine.core.instructions`</entry>
            </refactorings>
        </breaking>
        <additions>
            <entry>InstructionSetMigrator, to migrate instruction sets files throughout all (upcoming) versions</entry>
            <entry>InstructionSetOptionParser</entry>
            <entry>ConcreteCompiledStep class, representing a working default implementation</entry>
            <entry>ConcreteStepHandlerRegistry singleton, containing all "singleton" instruction step handlers</entry>
            <entry>InstructionPrecompilerStage, default precompilation stage, to convert ConfigInstructions into ChainedInstructions</entry>
            <entry>InstructionStepPrecompilerStage, default step precompilation stage, to convert ConfigSteps into fitting IStepHandler. Used by InstructionPrecompilerStage.</entry>
        </additions>
        <refactorings>
            <entry>XmlConstants to contain tags and attributes of the new XML file structure</entry>
            <entry>InstructionParser, to only have the responsibility of parsing the actual instructions</entry>
            <entry>InstructionParser, to use the new StepHandlerRegistry</entry>
            <entry>CoreConfig, to store a precompilation pipeline</entry>
            <entry>CoreConfigParser, to use the precompilation pipeline</entry>
        </refactorings>
    </category>
    <category name="instructions">
        <breaking kind="major">
            <refactorings>
                <entry>default instruction set file</entry>
                <entry>all `*Instruction.java` files, to be `*StepHandler.java` files in the new instruction layout</entry>
            </refactorings>
        </breaking>
    </category>
</patch>

=== TiJ-code/Registermaschine/changelogs/patches/v1_1_0_p01_changelog_system.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE patch SYSTEM "../patch.dtd">
<patch>
    <category name="dev-tools">
        <additions>
            <entry>Versioning dev-tool, that does the version bumps</entry>
            <entry>ConfigPatchParser dev-tool, that cumulates all patches into one `cumulated.xml`</entry>
            <entry>ConfigFileBuilder dev-tool, that builds the CHANGELOG.md from the cumulated XML file</entry>
        </additions>
        <refactorings>
            <entry>the release workflow to use the dev-tools instead</entry>
        </refactorings>
    </category>
</patch>

=== TiJ-code/Registermaschine/changelogs/patches/external_devices.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE patch SYSTEM "../patch.dtd">
<patch>
    <category name="api">
        <breaking kind="minor">
            <additions>
                <entry>memory interaction methods to IExecutionContext</entry>
                <entry>event listener methods for memory interactions to IExecutionContextListener</entry>
            </additions>
        </breaking>
        <additions>
            <entry>ConfigDevice that represents the configured XML structure for a device</entry>
            <entry>ConfigMemoryMapping that represents the configured XML structure for a memory mapping</entry>
            <entry>IDevice interface to create memory devices</entry>
            <entry>IMemoryMapping interface to create memory mapped devices</entry>
            <entry>OutOfMemoryException that will be thrown if the host system has not enough memory</entry>
        </additions>
    </category>
    <category name="core">
        <breaking kind="minor">
            <refactorings>
                <entry>the instruction set DTD file to accommodate the new device structure</entry>
            </refactorings>
        </breaking>
        <additions>
            <entry>ExternalDeviceParser that will parse the XML structure of devices and their mappings</entry>
            <entry>more XML tag and attribute constants to XmlConstants</entry>
            <entry>MemoryBus that is orchestrating all the memory interactions</entry>
            <entry>DeviceFactory to create and register IDevice and IMemoryMapping instances</entry>
        </additions>
    </category>
</patch>

=== TiJ-code/Registermaschine/changelogs/patches/v1_1_0_p02_plugin_system.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE patch SYSTEM "../patch.dtd">
<patch>
    <category name="api">
        <additions>
            <entry>IPlugin interface, that describes the plugin structure</entry>
            <entry>PluginContext record, that communicates registered instructions between loader and plugin</entry>
            <entry>IInstructionRegistry interface, that describes the layout of instruction registry implementations</entry>
        </additions>
    </category>
    <category name="core">
        <breaking kind="trivial">
            <additions>
                <entry>PluginLoader class, that can load (valid) plugins</entry>
            </additions>
        </breaking>
        <breaking kind="minor">
            <additions>
                <entry>ConcreteInstructionRegistry, that is a global container of all possible instruction handlers registered at runtime</entry>
            </additions>
            <refactorings>
                <entry>CoreConfig to conform to new global instruction registry structure</entry>
                <entry>CoreConfigParser to conform to new global instruction registry structure</entry>
                <entry>InstructionParser to conform to new global instruction registry structure</entry>
            </refactorings>
        </breaking>
        <additions>
            <entry>PluginConfig, that describes plugin config file structure</entry>
            <entry>PluginConfigParser, XML parser that parses file into instances of PluginConfig</entry>
            <entry>PluginConstants, XML constants class</entry>
        </additions>
    </category>
    <category name="instructions">
        <breaking kind="minor">
            <additions>
                <entry>RegistermaschinePlugin class, that describes the functionality of this default plugin. And enforces to use as plugin structure.</entry>
                <entry>plugin.xml, that is the configuration of this default instruction set plugin.</entry>
            </additions>
            <refactorings>
                <entry>package structure of this new plugin</entry>
            </refactorings>
        </breaking>
    </category>
</patch>
